[book]
authors = ["Caido"]
language = "en"
multilingual = false
src = "src"
title = "Caido Documentation"

[preprocessor.pagetoc]
[output.html]
default-theme = "navy"
git-repository-url = "https://github.com/caido/documentation"
additional-css = ["theme/pagetoc.css", "theme/main.css"]
additional-js  = ["theme/pagetoc.js"]

[output.html.redirect]
"/configuration/default_listening_address.html" = "/configuration/listening_address.html"
"/features/workflows/convert.html" = "/features/testing/workflows/convert.html"
"/internals/httpql.html" = "/concepts/httpql.html"
"/internals/instances.html" = "/concepts/instances.html"
