name: Lint & Build
on:
  pull_request:

  push:
    branches:
      - 'main'

concurrency:
  group: validate-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install Mise
        uses: caido/action-mise-action@v3.2.0
        with:
          version: ${{ vars.CI__MISE_VERSION }} 

      - name: Install dependencies
        run: pnpm install

      - name: Lint JS
        run: pnpm lint-prod

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install Mise
        uses: caido/action-mise-action@v3.2.0
        with:
          version: ${{ vars.CI__MISE_VERSION }} 

      - name: Install dependencies
        run: pnpm install

      - name: Run build
        run: pnpm build
